name: "Shiori Bookmark"
<<<<<<< HEAD
version: "1.2.12"
=======
description: "Self-hosted bookmark manager"
version: "1.2.11"
>>>>>>> 6cf14fd68d9a66470c055e008147d939e45c0e2b
slug: "shiori"
description: "Self-hosted bookmark manager with Ingress support"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
backup: true
ingress: true
webui: "http://[HOST]:[PORT]"
ports:
  8080/tcp: null
map:
  - config:rw
  - share:rw
