name: "Shiori Bookmark"
description: "Self-hosted bookmark manager"
version: "1.2.9"
slug: "shiori"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
backup: cold
ports:
  8080/tcp: 8080
map:
  - config:rw
  - share:rw
options:
  port: 8080
schema:
  port: int(1024, 65535)  
