name: Shiori Bookmark
version: "1.0.1"
slug: shiori
description: "Self-hosted bookmark manager"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
ports:
  8080/tcp: 8080
schema:
  port: int
map:
  - config:rw
  - ssl:ro
  - addons:rw
  - backup:rw
  - media:rw
  - share:rw
  - data:rw
