name: "Shiori Bookmark"
description: "Self-hosted bookmark manager"
version: "1.2.12"
slug: "shiori"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
backup: true
ingress: true
webui: "http://[HOST]:[PORT]"
ports:
  8080/tcp: null
map:
  - config:rw
  - share:rw
