name: "Shiori Bookmark"
description: "Self-hosted bookmark manager"
version: "1.2.6"
slug: "shiori"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
backup: cold
ports:
  8080/tcp: 8080
map:
  - config:rw
  - ssl:ro
  - addons:rw
  - backup:rw
  - media:rw
  - share:rw
  - data:rw
