name: Shiori Bookmark
version: "1.0.8"
slug: shiori
description: "Self-hosted bookmark manager"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
ingress: true
ports:
  8080/tcp: 8080
map:
  - config:rw
  - ssl:ro
  - addons:rw
  - backup:rw
  - media:rw
  - share:rw
  - data:rw
