name: "Shiori Bookmark"
description: "Self-hosted bookmark manager"
version: "1.2.10"
slug: "shiori"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
backup: cold
ports:
  8080/tcp: 8080
map:
  - config:rw
  - share:rw
options:
  port: 8080
# Ingress possible (accès direct via l’UI HA)
ingress: true
ingress_port: 8080
panel_icon: "mdi:bookmark"
panel_title: "Shiori"
