name: "Shiori Bookmark"
description: "Self-hosted bookmark manager for Home Assistant"
version: "1.3.0"
slug: "shiori"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
backup: cold
ports:
  8080/tcp: 8080
ingress: true
ingress_port: 8080
panel_icon: "mdi:bookmark"
panel_title: "Shiori"
map:
  - config:rw
  - share:rw
options:
  port: 8080
schema:
  port: int(1024, 65535)

