name: "Shiori Bookmark"
description: "Self-hosted bookmark manager"
version: "1.2.16"
slug: "shiori"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
backup: cold
ports:
  8080/tcp: 8080
map:
  - config:rw
