name: "Squid"
description: "Squid HTTP/HTTPS Proxy"
version: "1.0.5"
slug: "squid"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
backup: cold
ports:
  3128/tcp: 3128
map:
  - config:rw
