name: "Squid"
description: "Squid HTTP/HTTPS Proxy"
version: "1.0.0"
slug: "squid"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
backup: cold
ports:
  8080/tcp: 8080
map:
  - config:rw
